#pragma once

/* DO NOT MODIFY CODE ABOVE UNLESS YOU KNOW WHAT YOU ARE DOING */

inline constexpr char ModelName[] = "STM32F411CET6";

//#define ELFE_STM32F103
#define ELFE_STM32F411
//#define ELFE_STM32H743
//#define ELFE_STM32H750

#define ELFE_STM32_USE_CMSIS 0
#define ELFE_STM32_FORCE_GENERIC 0

// #define ELFE_STM32_CUSTOM_HAL_LIB ""

#define ELFE_USE_EXCEPTIONS 0
#define ELFE_FORCE_RESULT_IMPLICIT_CONVERSION 1
#define ELFE_FORCE_IGNORE_UNUSED_RESULT 1
